package chsink

import (
	"bytes"
	"errors"
	"flag"
	"os"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite deploy/clickhouse/schema.sql")

const goldenSchema = "../../deploy/clickhouse/schema.sql"

func TestCreateDDLGolden(t *testing.T) {
	got, err := CreateDDL(DefaultSchemaOptions())
	if err != nil {
		t.Fatal(err)
	}
	if *update {
		if err := os.WriteFile(goldenSchema, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(goldenSchema)
	if err != nil {
		t.Fatalf("%v (run: go test ./internal/chsink -run Golden -update)", err)
	}
	if got != string(want) {
		t.Fatal("deploy/clickhouse/schema.sql is stale; run: go test ./internal/chsink -run Golden -update")
	}
}

func TestCreateDDLCustom(t *testing.T) {
	ddl, err := CreateDDL(SchemaOptions{Database: "metrics", RetentionDays: 60, SnapshotRetentionDays: 7})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"CREATE DATABASE IF NOT EXISTS metrics;",
		"CREATE TABLE IF NOT EXISTS metrics.mysql_digest_stats",
		"TTL window_end + INTERVAL 60 DAY",
		"TTL ts + INTERVAL 7 DAY",
		"DateTime('UTC')",
		"ttl_only_drop_parts = 1",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("DDL missing %q", want)
		}
	}
	if strings.Contains(ddl, "{{") {
		t.Error("unreplaced placeholder in DDL")
	}
}

func TestMigrateDDLTTL(t *testing.T) {
	ddl, err := MigrateDDL(SchemaOptions{Database: "obs", RetentionDays: 90, SnapshotRetentionDays: 3})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(ddl, "-- Generated by: obs-agent clickhouse-schema -alter -database obs -retention 90d -snapshot-retention 3d\n") {
		t.Errorf("unexpected header:\n%s", ddl)
	}
	if n := strings.Count(ddl, "MODIFY TTL"); n != 6 {
		t.Fatalf("MODIFY TTL statements = %d, want 6 (every table but mysql_digest_text)\n%s", n, ddl)
	}
	for _, want := range []string{
		"ALTER TABLE obs.mysql_digest_stats MODIFY TTL window_end + INTERVAL 90 DAY;",
		"ALTER TABLE obs.mysql_slow_queries MODIFY TTL toDateTime(ts) + INTERVAL 90 DAY;",
		"ALTER TABLE obs.host_stats MODIFY TTL window_end + INTERVAL 90 DAY;",
		"ALTER TABLE obs.diagnose_snapshots MODIFY TTL ts + INTERVAL 3 DAY;",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("missing %q", want)
		}
	}
	if strings.Contains(ddl, "mysql_digest_text") {
		t.Error("mysql_digest_text has no TTL and must not be altered")
	}
	if strings.Contains(ddl, "{{") {
		t.Error("unreplaced placeholder in migration")
	}
}

func TestCreateDDLHasDiskColumnsAndHostStats(t *testing.T) {
	ddl, err := CreateDDL(DefaultSchemaOptions())
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"disk_read_bytes  UInt64", "disk_write_bytes UInt64", "io_wait_ns       Nullable(UInt64)", "redo_wait_ns     Nullable(UInt64)",
		"CREATE TABLE IF NOT EXISTS obs.host_stats", "cpu_count        UInt16", "node_cpu_used_ns Nullable(UInt64)",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("CREATE DDL lacks %q", want)
		}
	}
	if strings.Contains(ddl, "bytes_in") {
		t.Error("bytes_in must be gone from mysql_digest_stats")
	}
}

func TestMigrateDDL(t *testing.T) {
	out, err := MigrateDDL(SchemaOptions{Database: "obs", RetentionDays: 60, SnapshotRetentionDays: 14})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"ALTER TABLE obs.mysql_digest_stats ADD COLUMN IF NOT EXISTS disk_read_bytes UInt64 AFTER bytes_out",
		"ADD COLUMN IF NOT EXISTS redo_wait_ns Nullable(UInt64) AFTER io_wait_ns",
		"DROP COLUMN IF EXISTS bytes_in",
		"CREATE TABLE IF NOT EXISTS obs.host_stats",
		"ALTER TABLE obs.host_stats MODIFY TTL window_end + INTERVAL 60 DAY;",
		"ALTER TABLE obs.diagnose_snapshots MODIFY TTL ts + INTERVAL 14 DAY;",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("migration lacks %q", want)
		}
	}
	if strings.Index(out, "CREATE TABLE IF NOT EXISTS obs.host_stats") > strings.Index(out, "ALTER TABLE obs.host_stats MODIFY TTL") {
		t.Error("host_stats must be created before its TTL is modified")
	}
}

func TestParseRetentionDays(t *testing.T) {
	for in, want := range map[string]int{"30d": 30, "1d": 1, "3650d": 3650} {
		if got, err := ParseRetentionDays(in); err != nil || got != want {
			t.Errorf("ParseRetentionDays(%q) = %d, %v", in, got, err)
		}
	}
	for _, in := range []string{"0d", "-1d", "30", "30h", "abc", "", "3651d"} {
		if _, err := ParseRetentionDays(in); err == nil {
			t.Errorf("ParseRetentionDays(%q) accepted", in)
		}
	}
}

func TestRunSchemaCommand(t *testing.T) {
	var out, errb bytes.Buffer
	if code := RunSchemaCommand([]string{"-database", "x", "-retention", "10d"}, &out, &errb); code != 0 {
		t.Fatalf("exit %d: %s", code, errb.String())
	}
	if !strings.Contains(out.String(), "CREATE TABLE IF NOT EXISTS x.family_stats") || !strings.Contains(out.String(), "INTERVAL 10 DAY") {
		t.Fatalf("unexpected output:\n%s", out.String())
	}
	out.Reset()
	if code := RunSchemaCommand([]string{"-alter"}, &out, &errb); code != 0 ||
		!strings.Contains(out.String(), "-- Generated by: obs-agent clickhouse-schema -alter ") ||
		!strings.Contains(out.String(), "DROP COLUMN IF EXISTS bytes_in") ||
		!strings.Contains(out.String(), "ALTER TABLE obs.host_stats MODIFY TTL") {
		t.Fatalf("-alter: exit %d out %s", code, out.String())
	}
	errb.Reset()
	if code := RunSchemaCommand([]string{"-database", "bad-name"}, &out, &errb); code != 2 || !strings.Contains(errb.String(), "database") {
		t.Fatalf("bad database: exit %d stderr %q", code, errb.String())
	}
}

type failWriter struct{}

func (failWriter) Write([]byte) (int, error) { return 0, errors.New("broken pipe") }

func TestRunSchemaCommandStdoutWriteError(t *testing.T) {
	var errb bytes.Buffer
	if code := RunSchemaCommand(nil, failWriter{}, &errb); code != 1 || !strings.Contains(errb.String(), "broken pipe") {
		t.Fatalf("exit %d, stderr %q; want 1 and the write error", code, errb.String())
	}
}
