// Package chsink exports drained agent data to ClickHouse over its HTTP
// interface. The agent never runs DDL: this file only *prints* the schema
// (obs-agent clickhouse-schema) for an operator to apply.
package chsink

import (
	"flag"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/manhvu1997/linux-obs-agent/internal/config"
)

const (
	TableDigestStats = "mysql_digest_stats"
	TableDigestText  = "mysql_digest_text"
	TableSlowQueries = "mysql_slow_queries"
	TablePeerStats   = "netflow_peer_stats"
	TableFamilyStats = "family_stats"
	TableHostStats   = "host_stats"
	TableSnapshots   = "diagnose_snapshots"

	maxRetentionDays = 3650
)

// SchemaOptions parameterises the generated DDL.
type SchemaOptions struct {
	Database              string
	RetentionDays         int
	SnapshotRetentionDays int
}

func DefaultSchemaOptions() SchemaOptions {
	return SchemaOptions{Database: "obs", RetentionDays: 30, SnapshotRetentionDays: 14}
}

func (o SchemaOptions) validate() error {
	if !config.ValidClickHouseIdentifier(o.Database) {
		return fmt.Errorf("database %q must match ^[A-Za-z_][A-Za-z0-9_]*$", o.Database)
	}
	for name, d := range map[string]int{"retention": o.RetentionDays, "snapshot-retention": o.SnapshotRetentionDays} {
		if d < 1 || d > maxRetentionDays {
			return fmt.Errorf("%s must be between 1d and %dd", name, maxRetentionDays)
		}
	}
	return nil
}

// ParseRetentionDays parses "<N>d" with 1 <= N <= 3650.
func ParseRetentionDays(s string) (int, error) {
	n, err := strconv.Atoi(strings.TrimSuffix(s, "d"))
	if !strings.HasSuffix(s, "d") || err != nil || n < 1 || n > maxRetentionDays {
		return 0, fmt.Errorf("retention %q must look like 30d (1d..%dd)", s, maxRetentionDays)
	}
	return n, nil
}

// ttlTables lists every table with a TTL: name, TTL time expression, and
// whether it uses the snapshot retention.
var ttlTables = []struct {
	name, expr string
	snapshot   bool
}{
	{TableDigestStats, "window_end", false},
	{TableSlowQueries, "toDateTime(ts)", false},
	{TablePeerStats, "window_end", false},
	{TableFamilyStats, "window_end", false},
	{TableHostStats, "window_end", false},
	{TableSnapshots, "ts", true},
}

func (o SchemaOptions) replacer() *strings.Replacer {
	return strings.NewReplacer("{{db}}", o.Database,
		"{{ret}}", strconv.Itoa(o.RetentionDays), "{{snap}}", strconv.Itoa(o.SnapshotRetentionDays))
}

// CreateDDL returns the full CREATE script.
func CreateDDL(o SchemaOptions) (string, error) {
	if err := o.validate(); err != nil {
		return "", err
	}
	return o.replacer().Replace(createTemplate), nil
}

// migrateTemplate brings an existing database to the current schema. Every
// statement is idempotent.
const migrateTemplate = `ALTER TABLE {{db}}.mysql_digest_stats ADD COLUMN IF NOT EXISTS disk_read_bytes UInt64 AFTER bytes_out,
  ADD COLUMN IF NOT EXISTS disk_write_bytes UInt64 AFTER disk_read_bytes,
  ADD COLUMN IF NOT EXISTS io_wait_ns Nullable(UInt64) AFTER disk_write_bytes,
  ADD COLUMN IF NOT EXISTS redo_wait_ns Nullable(UInt64) AFTER io_wait_ns,
  DROP COLUMN IF EXISTS bytes_in;
`

// MigrateDDL returns the statements that upgrade an existing database
// (columns, new tables) followed by ALTER ... MODIFY TTL for every table, so
// one command both migrates and changes retention.
func MigrateDDL(o SchemaOptions) (string, error) {
	if err := o.validate(); err != nil {
		return "", err
	}
	r := o.replacer()
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by: obs-agent clickhouse-schema -alter -database %s -retention %dd -snapshot-retention %dd\n",
		o.Database, o.RetentionDays, o.SnapshotRetentionDays)
	b.WriteString(r.Replace(migrateTemplate))
	b.WriteString("\n")
	b.WriteString(r.Replace(hostStatsTemplate))
	b.WriteString("\n")
	for _, t := range ttlTables {
		days := o.RetentionDays
		if t.snapshot {
			days = o.SnapshotRetentionDays
		}
		fmt.Fprintf(&b, "ALTER TABLE %s.%s MODIFY TTL %s + INTERVAL %d DAY;\n", o.Database, t.name, t.expr, days)
	}
	return b.String(), nil
}

// RunSchemaCommand implements `obs-agent clickhouse-schema`. Exit codes:
// 0 ok, 1 output write failed, 2 bad arguments.
func RunSchemaCommand(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("clickhouse-schema", flag.ContinueOnError)
	fs.SetOutput(stderr)
	def := DefaultSchemaOptions()
	db := fs.String("database", def.Database, "ClickHouse database name")
	ret := fs.String("retention", strconv.Itoa(def.RetentionDays)+"d", "retention for stats/events tables, e.g. 30d")
	snap := fs.String("snapshot-retention", strconv.Itoa(def.SnapshotRetentionDays)+"d", "retention for diagnose_snapshots")
	alter := fs.Bool("alter", false, "print the migration for an existing database (new columns and tables) and ALTER ... MODIFY TTL, instead of CREATE")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	o := SchemaOptions{Database: *db}
	var err error
	if o.RetentionDays, err = ParseRetentionDays(*ret); err != nil {
		_, _ = fmt.Fprintln(stderr, err)
		return 2
	}
	if o.SnapshotRetentionDays, err = ParseRetentionDays(*snap); err != nil {
		_, _ = fmt.Fprintln(stderr, err)
		return 2
	}
	gen := CreateDDL
	if *alter {
		gen = MigrateDDL
	}
	out, err := gen(o)
	if err != nil {
		_, _ = fmt.Fprintln(stderr, err)
		return 2
	}
	if _, err := fmt.Fprint(stdout, out); err != nil {
		_, _ = fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}

const createTemplate = `-- Generated by: obs-agent clickhouse-schema -database {{db}} -retention {{ret}}d -snapshot-retention {{snap}}d
-- Apply:                      clickhouse-client --multiquery < schema.sql
-- Migrate / change retention: obs-agent clickhouse-schema -alter -retention 60d | clickhouse-client --multiquery
--   (upgrade the agents first: -alter drops a column older agents still send)

CREATE DATABASE IF NOT EXISTS {{db}};

-- The agent only needs INSERT. Run once as an admin:
-- CREATE USER IF NOT EXISTS obs_agent IDENTIFIED WITH sha256_password BY '<password>';
-- GRANT INSERT ON {{db}}.* TO obs_agent;

CREATE TABLE IF NOT EXISTS {{db}}.mysql_digest_stats (
  window_start     DateTime('UTC'),
  window_end       DateTime('UTC'),
  host             LowCardinality(String),
  pid              UInt32,
  digest_id        String,
  command          LowCardinality(String),
  calls            UInt64,
  cpu_ns           UInt64,
  runq_ns          UInt64,
  wall_ns          UInt64,
  wall_max_ns      UInt64,
  bytes_out        UInt64,
  disk_read_bytes  UInt64,
  disk_write_bytes UInt64,
  io_wait_ns       Nullable(UInt64),
  redo_wait_ns     Nullable(UInt64)
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, digest_id, window_end)
TTL window_end + INTERVAL {{ret}} DAY
SETTINGS ttl_only_drop_parts = 1;

-- One row per distinct digest; no TTL (small, labels old stats).
CREATE TABLE IF NOT EXISTS {{db}}.mysql_digest_text (
  digest_id    String,
  digest_text  String,
  sample_query Nullable(String),
  first_seen   DateTime('UTC')
) ENGINE = ReplacingMergeTree(first_seen)
ORDER BY digest_id;

CREATE TABLE IF NOT EXISTS {{db}}.mysql_slow_queries (
  ts          DateTime64(3, 'UTC'),
  host        LowCardinality(String),
  pid         UInt32,
  tid         UInt32,
  comm        LowCardinality(String),
  latency_ms  Float64,
  digest_id   String,
  query       String
) ENGINE = MergeTree
PARTITION BY toDate(ts)
ORDER BY (host, ts)
TTL toDateTime(ts) + INTERVAL {{ret}} DAY
SETTINGS ttl_only_drop_parts = 1;

CREATE TABLE IF NOT EXISTS {{db}}.netflow_peer_stats (
  window_start DateTime('UTC'),
  window_end   DateTime('UTC'),
  host         LowCardinality(String),
  family       LowCardinality(String),
  pid          UInt32,
  comm         LowCardinality(String),
  direction    LowCardinality(String),
  peer_ip      IPv6,
  service_port UInt16,
  bytes_rx     UInt64,
  bytes_tx     UInt64,
  conns_opened UInt64,
  conns_closed UInt64
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, family, direction, peer_ip, window_end)
TTL window_end + INTERVAL {{ret}} DAY
SETTINGS ttl_only_drop_parts = 1;

CREATE TABLE IF NOT EXISTS {{db}}.family_stats (
  window_start    DateTime('UTC'),
  window_end      DateTime('UTC'),
  host            LowCardinality(String),
  family          LowCardinality(String),
  cpu_percent_avg Float32,
  cpu_percent_max Float32,
  rss_bytes_max   UInt64,
  processes_max   UInt32
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, family, window_end)
TTL window_end + INTERVAL {{ret}} DAY
SETTINGS ttl_only_drop_parts = 1;

` + hostStatsTemplate + `
CREATE TABLE IF NOT EXISTS {{db}}.diagnose_snapshots (
  ts      DateTime('UTC'),
  host    LowCardinality(String),
  reason  LowCardinality(String),
  verdict LowCardinality(String),
  report  String CODEC(ZSTD(3))
) ENGINE = MergeTree
PARTITION BY toDate(ts)
ORDER BY (host, ts)
TTL ts + INTERVAL {{snap}} DAY
SETTINGS ttl_only_drop_parts = 1;
`

// hostStatsTemplate is shared by createTemplate and MigrateDDL so the table
// has one definition.
const hostStatsTemplate = `-- Denominators per host and flush interval (shares over any range). NULL =
-- that interval had a poll without a valid delta.
CREATE TABLE IF NOT EXISTS {{db}}.host_stats (
  window_start     DateTime('UTC'),
  window_end       DateTime('UTC'),
  host             LowCardinality(String),
  cpu_count        UInt16,
  node_cpu_used_ns Nullable(UInt64),
  mysqld_cpu_ns    Nullable(UInt64),
  disk_read_bytes  Nullable(UInt64),
  disk_write_bytes Nullable(UInt64)
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, window_end)
TTL window_end + INTERVAL {{ret}} DAY
SETTINGS ttl_only_drop_parts = 1;
`
