-- Generated by: obs-agent clickhouse-schema -database obs -retention 30d -snapshot-retention 14d
-- Apply:            clickhouse-client --multiquery < schema.sql
-- Change retention: obs-agent clickhouse-schema -alter -retention 60d | clickhouse-client --multiquery

CREATE DATABASE IF NOT EXISTS obs;

-- The agent only needs INSERT. Run once as an admin:
-- CREATE USER IF NOT EXISTS obs_agent IDENTIFIED WITH sha256_password BY '<password>';
-- GRANT INSERT ON obs.* TO obs_agent;

CREATE TABLE IF NOT EXISTS obs.mysql_digest_stats (
  window_start     DateTime('UTC'),
  window_end       DateTime('UTC'),
  host             LowCardinality(String),
  pid              UInt32,
  digest_id        String,
  command          LowCardinality(String),
  calls            UInt64,
  cpu_ns           UInt64,
  runq_ns          UInt64,
  wall_ns          UInt64,
  wall_max_ns      UInt64,
  bytes_out        UInt64,
  disk_read_bytes  UInt64,
  disk_write_bytes UInt64,
  io_wait_ns       Nullable(UInt64),
  redo_wait_ns     Nullable(UInt64)
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, digest_id, window_end)
TTL window_end + INTERVAL 30 DAY
SETTINGS ttl_only_drop_parts = 1;

-- One row per distinct digest; no TTL (small, labels old stats).
CREATE TABLE IF NOT EXISTS obs.mysql_digest_text (
  digest_id    String,
  digest_text  String,
  sample_query Nullable(String),
  first_seen   DateTime('UTC')
) ENGINE = ReplacingMergeTree(first_seen)
ORDER BY digest_id;

CREATE TABLE IF NOT EXISTS obs.mysql_slow_queries (
  ts          DateTime64(3, 'UTC'),
  host        LowCardinality(String),
  pid         UInt32,
  tid         UInt32,
  comm        LowCardinality(String),
  latency_ms  Float64,
  digest_id   String,
  query       String
) ENGINE = MergeTree
PARTITION BY toDate(ts)
ORDER BY (host, ts)
TTL toDateTime(ts) + INTERVAL 30 DAY
SETTINGS ttl_only_drop_parts = 1;

CREATE TABLE IF NOT EXISTS obs.netflow_peer_stats (
  window_start DateTime('UTC'),
  window_end   DateTime('UTC'),
  host         LowCardinality(String),
  family       LowCardinality(String),
  pid          UInt32,
  comm         LowCardinality(String),
  direction    LowCardinality(String),
  peer_ip      IPv6,
  service_port UInt16,
  bytes_rx     UInt64,
  bytes_tx     UInt64,
  conns_opened UInt64,
  conns_closed UInt64
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, family, direction, peer_ip, window_end)
TTL window_end + INTERVAL 30 DAY
SETTINGS ttl_only_drop_parts = 1;

CREATE TABLE IF NOT EXISTS obs.family_stats (
  window_start    DateTime('UTC'),
  window_end      DateTime('UTC'),
  host            LowCardinality(String),
  family          LowCardinality(String),
  cpu_percent_avg Float32,
  cpu_percent_max Float32,
  rss_bytes_max   UInt64,
  processes_max   UInt32
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, family, window_end)
TTL window_end + INTERVAL 30 DAY
SETTINGS ttl_only_drop_parts = 1;

-- Denominators per host and flush interval (shares over any range). NULL =
-- that interval had a poll without a valid delta.
CREATE TABLE IF NOT EXISTS obs.host_stats (
  window_start     DateTime('UTC'),
  window_end       DateTime('UTC'),
  host             LowCardinality(String),
  cpu_count        UInt16,
  node_cpu_used_ns Nullable(UInt64),
  mysqld_cpu_ns    Nullable(UInt64),
  disk_read_bytes  Nullable(UInt64),
  disk_write_bytes Nullable(UInt64)
) ENGINE = MergeTree
PARTITION BY toDate(window_end)
ORDER BY (host, window_end)
TTL window_end + INTERVAL 30 DAY
SETTINGS ttl_only_drop_parts = 1;

CREATE TABLE IF NOT EXISTS obs.diagnose_snapshots (
  ts      DateTime('UTC'),
  host    LowCardinality(String),
  reason  LowCardinality(String),
  verdict LowCardinality(String),
  report  String CODEC(ZSTD(3))
) ENGINE = MergeTree
PARTITION BY toDate(ts)
ORDER BY (host, ts)
TTL ts + INTERVAL 14 DAY
SETTINGS ttl_only_drop_parts = 1;
